package net.suntec.framework.constant;

public interface MessageConstant {
	String MSG_SYSTEM_FAILED = "MSG_SYSTEM_FAILED";
	String MSG_AUTHENTICATE_FAILED = "MSG_AUTHENTICATE_FAILED";
	String MSG_TOKEN_FAILED = "MSG_TOKEN_FAILED";
	String MSG_HEADER_FAILED = "MSG_HEADER_FAILED";
	String MSG_AGREE_AND_BIND_FAILED = "MSG_AGREE_AND_BIND_FAILED";
	String MSG_GET_CLIENTID = "MSG_GET_CLIENTID";
	String MSG_LOGOUT_FAILED = "MSG_LOGOUT_FAILED";
	String MSG_LIST_BINDS_FAILED = "MSG_LIST_BINDS_FAILED";
	String MSG_UN_BIND_FAILED = "MSG_UN_BIND_FAILED";
	String MSG_AGREE_SWITCH_FAILED = "MSG_AGREE_SWITCH_FAILED";
	String MSG_FETCH_AGREE_SWITCH_FAILED = "MSG_FETCH_AGREE_SWITCH_FAILED";
}
